TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devtriton.db
DATA += devtriton.proto

#=======================================
include $(TOP)/configure/RULES
